-- MySQL Script generated by MySQL Workbench
-- 09/22/17 18:30:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sellcompany
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sellcompany` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sellcompany` ;

-- -----------------------------------------------------
-- Table `sellcompany`.`SHOPTYPES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`SHOPTYPES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SHOPTYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idSHOPTYPE_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`COUNTRIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`COUNTRIES` (
  `idCOUNTRIES` INT NOT NULL AUTO_INCREMENT,
  `COUNTRY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCOUNTRIES`),
  UNIQUE INDEX `idCOUNTRIES_UNIQUE` (`idCOUNTRIES` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`CITIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`CITIES` (
  `idCITIES` INT NOT NULL AUTO_INCREMENT,
  `CITY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCITIES`),
  UNIQUE INDEX `idCITIES_UNIQUE` (`idCITIES` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`ADDRESSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`ADDRESSES` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `COUNTRIES_ID` INT NULL,
  `CITIES_ID` INT NULL,
  `STREET` VARCHAR(45) BINARY NOT NULL,
  `HOUSE_NUM` INT NOT NULL,
  PRIMARY KEY (`idAddress`),
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC),
  INDEX `fk_ADDRESS_COUNTRIES_idx` (`COUNTRIES_ID` ASC),
  INDEX `fk_ADDRESS_CITIES1_idx` (`CITIES_ID` ASC),
  CONSTRAINT `fk_ADDRESS_COUNTRIES`
    FOREIGN KEY (`COUNTRIES_ID`)
    REFERENCES `sellcompany`.`COUNTRIES` (`idCOUNTRIES`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_ADDRESS_CITIES1`
    FOREIGN KEY (`CITIES_ID`)
    REFERENCES `sellcompany`.`CITIES` (`idCITIES`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`SUPERMARKETS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`SUPERMARKETS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SHOPTYPE_ID` INT NULL,
  `ADDRESSES_ID` INT NOT NULL,
  `STAFF_NUM` VARCHAR(45) NOT NULL,
  `NEW_ARRIVAL_DATE` DATE NOT NULL,
  `SQUARE` INT NOT NULL,
  `SECTION_NUM` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idShops_UNIQUE` (`ID` ASC),
  INDEX `fk_SUPERMARKETS_SHOPTYPE1_idx` (`SHOPTYPE_ID` ASC),
  INDEX `fk_SUPERMARKETS_ADDRESSES1_idx` (`ADDRESSES_ID` ASC),
  CONSTRAINT `fk_SUPERMARKETS_SHOPTYPE1`
    FOREIGN KEY (`SHOPTYPE_ID`)
    REFERENCES `sellcompany`.`SHOPTYPES` (`ID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_SUPERMARKETS_ADDRESSES1`
    FOREIGN KEY (`ADDRESSES_ID`)
    REFERENCES `sellcompany`.`ADDRESSES` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`ONLINESHOPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`ONLINESHOPS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SHOPTYPE_ID` INT NULL,
  `ADDRESSES_ID` INT NOT NULL,
  `STAFF_NUM` VARCHAR(45) NOT NULL,
  `NEW_ARRIVAL_DATE` DATE NOT NULL,
  `SITE` VARCHAR(45) NOT NULL,
  `MANAGERS_NUM` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idShops_UNIQUE` (`ID` ASC),
  INDEX `fk_ONLINESHOP_SHOPTYPE1_idx` (`SHOPTYPE_ID` ASC),
  INDEX `fk_ONLINESHOP_ADDRESSES1_idx` (`ADDRESSES_ID` ASC),
  CONSTRAINT `fk_ONLINESHOP_SHOPTYPE1`
    FOREIGN KEY (`SHOPTYPE_ID`)
    REFERENCES `sellcompany`.`SHOPTYPES` (`ID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_ONLINESHOP_ADDRESSES1`
    FOREIGN KEY (`ADDRESSES_ID`)
    REFERENCES `sellcompany`.`ADDRESSES` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`PAVILIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`PAVILIONS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SHOPTYPE_ID` INT NULL,
  `ADDRESSES_ID` INT NOT NULL,
  `STAFF_NUM` VARCHAR(45) NOT NULL,
  `NEW_ARRIVAL_DATE` DATE NOT NULL,
  `PLACE_NUM` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idShops_UNIQUE` (`ID` ASC),
  INDEX `fk_PAVILION_SHOPTYPE1_idx` (`SHOPTYPE_ID` ASC),
  INDEX `fk_PAVILION_ADDRESSES1_idx` (`ADDRESSES_ID` ASC),
  CONSTRAINT `fk_PAVILION_SHOPTYPE1`
    FOREIGN KEY (`SHOPTYPE_ID`)
    REFERENCES `sellcompany`.`SHOPTYPES` (`ID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_PAVILION_ADDRESSES1`
    FOREIGN KEY (`ADDRESSES_ID`)
    REFERENCES `sellcompany`.`ADDRESSES` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`LOGISTICSTORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`LOGISTICSTORES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `ADDRESSES_ID` INT NOT NULL,
  `SQAURE` INT NOT NULL,
  `LOADER_NUM` INT NOT NULL,
  `NEW_ARRIVAL_DATE` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_LOGISTICSTORE_ADDRESSES1_idx` (`ADDRESSES_ID` ASC),
  CONSTRAINT `fk_LOGISTICSTORE_ADDRESSES1`
    FOREIGN KEY (`ADDRESSES_ID`)
    REFERENCES `sellcompany`.`ADDRESSES` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`FACTORYSTORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`FACTORYSTORES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `ADDRESSES_ID` INT NOT NULL,
  `SQAURE` INT NOT NULL,
  `LOADER_NUM` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_FACTORYSTORE_ADDRESSES1_idx` (`ADDRESSES_ID` ASC),
  CONSTRAINT `fk_FACTORYSTORE_ADDRESSES1`
    FOREIGN KEY (`ADDRESSES_ID`)
    REFERENCES `sellcompany`.`ADDRESSES` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`PRODUCERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`PRODUCERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCER` VARCHAR(45) NOT NULL,
  `ORDERS_NUM` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`LOGISTICSTORES_has_PRODUCERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`LOGISTICSTORES_has_PRODUCERS` (
  `LOGISTICSTORES_ID` INT NOT NULL,
  `PRODUCERS_ID` INT NOT NULL,
  INDEX `fk_LOGISTICSTORES_has_PRODUCERS_PRODUCERS1_idx` (`PRODUCERS_ID` ASC),
  INDEX `fk_LOGISTICSTORES_has_PRODUCERS_LOGISTICSTORES1_idx` (`LOGISTICSTORES_ID` ASC),
  CONSTRAINT `fk_LOGISTICSTORES_has_PRODUCERS_LOGISTICSTORES1`
    FOREIGN KEY (`LOGISTICSTORES_ID`)
    REFERENCES `sellcompany`.`LOGISTICSTORES` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LOGISTICSTORES_has_PRODUCERS_PRODUCERS1`
    FOREIGN KEY (`PRODUCERS_ID`)
    REFERENCES `sellcompany`.`PRODUCERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`GOODS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`GOODS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GOOD` VARCHAR(45) NOT NULL,
  `AMOUNT` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sellcompany`.`FACTORYSTORES_has_GOODS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcompany`.`FACTORYSTORES_has_GOODS` (
  `FACTORYSTORES_ID` INT NOT NULL,
  `GOODS_ID` INT NOT NULL,
  INDEX `fk_FACTORYSTORES_has_GOODS_GOODS1_idx` (`GOODS_ID` ASC),
  INDEX `fk_FACTORYSTORES_has_GOODS_FACTORYSTORES1_idx` (`FACTORYSTORES_ID` ASC),
  CONSTRAINT `fk_FACTORYSTORES_has_GOODS_FACTORYSTORES1`
    FOREIGN KEY (`FACTORYSTORES_ID`)
    REFERENCES `sellcompany`.`FACTORYSTORES` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FACTORYSTORES_has_GOODS_GOODS1`
    FOREIGN KEY (`GOODS_ID`)
    REFERENCES `sellcompany`.`GOODS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
